module.exports = {
  npmStat: {
    parallelRequests: 20,
    packages: [
      '@guidesmiths/cuckoojs-cli',
      '@guidesmiths/cuckoojs-schematics',
      '@guidesmiths/generator-react-component',
      '@onebeyond/license-checker',
      '@guidesmiths/react-form-builder',
      '@guidesmiths/react-form-creator',
      '@guidesmiths/systemic-aws-s3',
      '@guidesmiths/systemic-aws-sqs',
      '@onebeyond/systemic-knex',
      'acdc',
      'adblock-plus-crx',
      'block-sequence',
      'block-sequence-compliance-tests',
      'block-sequence-mongo',
      'block-sequence-mysql',
      'block-sequence-postgres',
      'block-sequence-redis',
      'block-sequence-reference',
      'confabulous',
      'confabulous-etcd-loader',
      'confabulous-http-loader',
      'confabulous-postgres-loader',
      'confabulous-s3-loader',
      'confabulous-vault-loader',
      'dangerjs-wrapper',
      'error-handler-module',
      'eslint-config-imperative',
      'eslint-config-imperative-es6',
      'eslint-plugin-imperative',
      'generator-systemic',
      'groundhog-day',
      'gs-hygen',
      'handy-postgres',
      'hath-assert',
      'httq',
      'json-2-sql',
      'kube-deploy',
      'make-manifest',
      'marv',
      'marv-mysql-driver',
      'marv-pg-driver',
      'middleware-auth',
      'mr.robot',
      'node-madgex',
      'outstanding',
      'prepper',
      'prerelease-ftw',
      'qs3',
      'qsftp',
      'rascal',
      'react-native-uservoice',
      'refdata',
      'release-clerk',
      'request-token',
      'sql-params-format',
      'starscream',
      'stashback',
      'swagger-endpoint-validator',
      'systemic',
      'systemic-azure-bus',
      'systemic-azure-metrics',
      'systemic-domain-runner',
      'systemic-express',
      'systemic-github-api',
      'systemic-knex',
      'systemic-mongodb',
      'systemic-mongodb-memory-server',
      'systemic-mssql',
      'systemic-mysql',
      'systemic-pg',
      'systemic-rabbitmq',
      'systemic-redis',
      'systemic-service-runner',
      'systemic-slack',
      'whoosh',
      'worksmith',
      'worksmith_etcd',
      'worksmith_rascal',
      'worksmith_sftp',
      'world-clock'
    ]
  },
  cauldron: {
    reference: {
      grafana: 'https://cauldron.io/project/7192/public-kibana'
    },
    baseProjectUrl: 'https://cauldron.io/project/7192'
  },
  stepSecurity: {
    reference: {
      gs: 'https://app.stepsecurity.io/github/app/onebeyond/guidesmiths/repositories',
      ob: 'https://app.stepsecurity.io/github/app/onebeyond/onebeyond/repositories'
    },
    repositories: {
      gs: 'https://agent.api.stepsecurity.io/v1/app/customers/onebeyond/githubaccounts/guidesmiths/repositories',
      ob: 'https://agent.api.stepsecurity.io/v1/app/customers/onebeyond/githubaccounts/onebeyond/repositories'
    }
  }
}
